problem5/app/config/routes.rb
App::Application.routes.draw do
  get "sessions/new"
 
    resources :articles do
      resources 'comments'
    end
  resources :users do
    resources 'articles'
  end
  resources :countries
  
  get 'sign_up' => 'users#new', as: :sign_up
  get 'log_in' => 'sessions#new', as:  :log_in
  get 'log_out' =>'sessions#destroy', as: :log_out
  post 'post_login' => 'sessions#create', as: :post_login 
  
  resources :sessions
  resources :categories
  resources :products
  
  namespace :admin do
    resources :articles
    resources :products
    resources :categories
    resources :countries
    resources :users
  end
  

  root 'articles#index'

end

problem5/app/app/models/country.rb
class Country < ActiveRecord::Base
	validates :code, presence: {message: "please fill code field"}, inclusion: { in: %w(IDN USA CHN AUS HKG) }
	validates :name, presence: {message: "please fill name field"}

	has_many :users, inverse_of: :country
	has_many :user_indo, -> {where("country_id = 1")}, class_name: "User"
	
		def to_param
			name
		end
				
end

problem5/app/app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::ApplicationController
	before_filter :require_admin_login

	def index
		@countries=Country.all
	end

	def show
		@a=Country.find_by_name(params[:id])
	end
	def new
		@a=Country.new
	end
	def create
		@a = Country.new(c_params)	
		if @a.save 
			flash[:notice]="Country successfully added"
			redirect_to admin_countries_path
		else
		render 'new'
		end
	end

	def edit
		@a=Country.find_by_name(params[:id])
	end
	def update
		@a = Country.find_by_name(params[:id])
		if @a.update(c_params)
			flash[:notice]="Country successfully edited"
			redirect_to admin_countries_path
		else
			render 'edit'
		end
	end
	def destroy
		@a=Country.find_by_name(params[:id])
		@a.destroy
		flash[:notice]="Country deleted"
		redirect_to admin_countries_path
	end
	private
	 def c_params
	 	params.require(:country).permit(:code, :name)
	 end
	 	
end

problem5/app/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
 def new 
 	@a=Country.new
 end
 def index
 	@countries=Country.all
 end

 def create
 	@a = Country.new(c_params)	
	if @a.save 
		redirect_to @a
	else
		render 'new'
	end
 end

 def edit
 	@a=Country.find(params[:id])
 end

def update
	@a = Country.find(params[:id])
	if @a.update(c_params)
		redirect_to @a
	else
		render 'edit'
	end
end
def show
	@a=Country.find(params[:id])
end
def destroy
	@a=Country.find(params[:id])
	@a.destroy
	redirect_to countries_path
end

 private
 def c_params
 	params.require(:country).permit(:code, :name)
 end
 	
 

end

problem5/app/app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

problem5/app/app/helpers/countries_helper.rb
module CountriesHelper
end

problem5/app/app/views/countries/_form_country.html.erb
<%= form_for @a do |f| %>
 	<%= raw(valid_error_display(@a))%>
	<p>
	<%= f.label :code %><br>
	<%= f.text_field :code %>
	</p>

	<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

problem5/app/app/views/countries/edit.html.erb
<h1>Edit Country</h1>

<%=render "form_country"%>

<%=link_to "Back", countries_path%>

problem5/app/app/views/countries/index.html.erb
<h1>Countries List</h1>
<%= link_to 'Articles', articles_path%> | <%= link_to 'Countries', countries_path%> | <%= link_to "Users", users_path%> | <%= link_to "Products", products_path%> | <%= link_to "Categories", categories_path%>
<br>
 <%=link_to 'new', new_country_path%> <% if session[:user_id] %>
  <%= link_to("Logout", log_out_path) %>
<% else %>
  <%= link_to("Login", log_in_path) %>
<% end %>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
  </tr>
 
  <% @countries.each do |a| %>
    <tr>
      <td><%= a.code %></td>
      <td><%= a.name %></td>
      <td><%= link_to 'Show', country_path(a) %></td>
      <td><%=link_to "Edit", edit_country_path(a.id)%></td>
      <td><%=link_to "Delete", country_path(a.id),  method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

problem5/app/app/views/countries/new.html.erb
<h1>Insert New Country </h1>

<%= render 'form_country' %>

<%=link_to "Back", countries_path%>

problem5/app/app/views/countries/show.html.erb
<p>
<STRONG>Code : </STRONG>
<%=@a.code %>
</p>
<p>
<strong>Name :</strong>
<%=@a.name%>
</p>

<%=link_to "back", countries_path%>