problem5/app/config/routes.rb
App::Application.routes.draw do
  get "sessions/new"
 
    resources :articles do
      resources 'comments'
    end
  resources :users do
    resources 'articles'
  end
  resources :countries
  
  get 'sign_up' => 'users#new', as: :sign_up
  get 'log_in' => 'sessions#new', as:  :log_in
  get 'log_out' =>'sessions#destroy', as: :log_out
  post 'post_login' => 'sessions#create', as: :post_login 
  
  resources :sessions
  resources :categories
  resources :products
  
  namespace :admin do
    resources :articles
    resources :products
    resources :categories
    resources :countries
    resources :users
  end
  

  root 'articles#index'

end

problem5/app/app/models/product.rb
class Product < ActiveRecord::Base
	validates :price, numericality: {message: "Just numeric allowed"}, presence: {message: "please fill price field"}
	validates :stock, presence: {message: "please fill stock field"}
	validates :description, presence: {message: "please fill description field"}
	validates :name, presence: {message: "please fill name field"}

	belongs_to :user
	has_many :categorizations
	has_many :categories, :through => :categorizations

	scope :stock, lambda {|stock| where("stock = ?", stock)}  
	scope :stock_more_than, lambda {|stock| where("stock > ?", stock)}  
	scope :stock_less_than, lambda {|stock| where("stock < ?", stock)} 
	scope :find_price_less_1000, where("price < 1000") 

	def to_param
   		name
  	end
end

problem5/app/app/controllers/admin/products_controller.rb
class Admin::ProductsController <  Admin::ApplicationController
	before_filter :require_admin_login

	def index
	 	@p=Product.all.paginate(:page => params[:page], :per_page => 5)
	end

	def show
		@p=Product.find_by_name(params[:id])
	end

	def new
	 	@p=Product.new
	end 

	def create
		@user = current_user
		@p = Product.new(p_params)
		@p.user=@user
		
		if @p.save 
			flash[:notice]="Product succesfully created"
			redirect_to admin_product_path(@p)
		else
			render 'new'
		end
	end

	def edit
		@p=Product.find_by_name(params[:id])
	end
	def update
		@p = Product.find_by_name(params[:id])
		if @p.update(p_params)
			flash[:notice]="Product succesfully updated"
			redirect_to @p
		else
			render 'edit'
		end
	end

	def destroy
		@product=Product.find_by_name(params[:id])
		@product.destroy
		redirect_to admin_products_path
	end

	def p_params
		params.require(:product).permit(:name, :description, :stock, :price, :category_ids => [])
	end
end

problem5/app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
	before_filter :find_product, :only => [:edit, :update, :show, :destroy]
	before_action :correct_product_owner,   :only => [:edit, :update, :destroy]
	def index
		@products=Product.all
	end

	def new
		@p=Product.new
	end

	def create
		@user = current_user
		@p = Product.new(p_params)
		@p.user=@user
		
		if @p.save 
			flash[:notice]="Product created"
			redirect_to @p
		else
			render 'new'
		end
	end

	def show
		@p=Product.find_by_name(params[:id])

	end

	def edit
		@p=Product.find_by_name(params[:id])
	end
	def update
		@p = Product.find_by_name(params[:id])
		if @p.update(p_params)
			flash[:notice]="Product updated"
			redirect_to @p
		else
			render 'edit'
		end
	end
	def destroy
		@product=Product.find_by_name(params[:id])
		@product.destroy
		flash[:notice]="Product deleted"
		redirect_to current_user
	end

	private
	def p_params
		params.require(:product).permit(:name, :description, :stock, :price, :category_ids => [])
	end
	def find_product
      @product = Product.find_by_name(params[:id])
      if @product.nil?
        flash[:notice] = "Cannot find the product"
        redirect_to products_url
      end
  	end
end

problem5/app/app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

problem5/app/app/helpers/products_helper.rb
module ProductsHelper
end

problem5/app/app/views/products/_form_product.html.erb
<%= form_for @p do |f| %>
 <% if @p.errors.any? %>
  <div id="error_explanation">
    <h2>Error</h2>
    <ul>
    <% @p.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
	<p>
	<%= f.label :Edit_Name %><br>
	<%= f.text_field :name %>
	</p>
	<p>
	<%= f.label :Edit_Description %><br>
	<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

problem5/app/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%=render "form_product"%>

<%=link_to "back", products_path%>

problem5/app/app/views/products/index.html.erb
<div class="row">
  <div class="span12">
  <div class="page-header">
      <h3>Products</h3>
       <%= link_to 'New Product ', new_product_path, :class => "btn btn-primary" %>
  </div>
    <table class="table table-striped custab">
    <thead>
        <tr>
          <th>Product Name</th>
          <th>Description</th>  
          <th>Stock</th>
          <th>Price</th>
          <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @products.each do |a| %>
    <tr>
      <td><%=a.name%></td>
      <td><%=truncate(a.description, :length=>100)%></td>
      <td><%=a.stock%></td>
      <td><%=a.price%></td>
      <td><%=link_to "Show", product_path(a)%></td>
     
    </tr>
    <% end %>
    </tbody> 
    </table>  
  </div>
</div>

problem5/app/app/views/products/new.html.erb
<div class="page-header">
  <h3>New Products</h3>
</div>

<div class="row-fluid">
  <div class="span12">

  
    <%= raw(valid_error_display(@p))%>


<%= form_for @p , :html => {:class => 'form-horizontal'} do |f| %>
  <fieldset>
    <div class="control-group">
     
      <label class="control-label"  for="Title">Name</label>
      <div class="controls">
       <%= f.text_field :name, :class => "input-xlarge span8" %>
        <p class="help-block">Name your product</p>
      </div>
    </div>

    <div class="control-group">
     
      <label class="control-label" for="First name">Stock</label>
      <div class="controls">
       <%= f.text_field :stock, :class => "span8",:rows =>"8" %>
        <p class="help-block">Number only</p>
      </div>
    </div>

    <div class="control-group">
     
      <label class="control-label" for="First name">Price</label>
      <div class="controls">
       <%= f.text_field :price, :class => "span8",:rows =>"8" %>
        <p class="help-block">Number only</p>
      </div>
    </div>
    <div class="control-group">
     
      <label class="control-label" for="First name">Description</label>
      <div class="controls">
       <%= f.text_area :description, :class => "span8",:rows =>"8" %>
        <p class="help-block">Your product's description</p>
      </div>
    </div>

     <div class="control-group">
     
      <label class="control-label" for="First name">Category</label>
      <div class="controls">
       <%= collection_check_boxes(:product, :category_ids, Category.all, :id, :name) %>
        <p class="help-block">Your product's description</p>
      </div>
    </div>

    <div class="control-group">
      <!-- Button -->
      <div class="controls">
      <%= f.submit 'Submit', :class => 'btn btn-success' %> <%=link_to "Back", products_path, :class =>"btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<%end%>

  </div>
</div>

problem5/app/app/views/products/show.html.erb
<h1>Product Detail</h1>

<p>Product Name : <%=@p.name%></p>
<p>Description :<%=@p.description%></p>
<p>Creator : <%=link_to"#{@p.user.username}", user_path(@p.user.username)%></p>
<p>
	Category : <%@p.categories.each do |c|%>
	<%=link_to "#{c.name}", category_path(c.id)%>,
	<% end %>
</p>