problem5/app/config/routes.rb
App::Application.routes.draw do
  get "sessions/new"
 
    resources :articles do
      resources 'comments'
    end
  resources :users do
    resources 'articles'
  end
  resources :countries
  
  get 'sign_up' => 'users#new', as: :sign_up
  get 'log_in' => 'sessions#new', as:  :log_in
  get 'log_out' =>'sessions#destroy', as: :log_out
  post 'post_login' => 'sessions#create', as: :post_login 
  
  resources :sessions
  resources :categories
  resources :products
  
  namespace :admin do
    resources :articles
    resources :products
    resources :categories
    resources :countries
    resources :users
  end
  

  root 'articles#index'

end

problem5/app/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: {message: "can't be blank", allow_blank: false, allow_nil: false}, uniqueness: true
	validates :descriptions, presence: {message: "can't be blank"}

	

	has_many :comments, dependent: :destroy
	belongs_to :user
	
	scope :rate, lambda {|r| where("rating = ?", r)}  
	scope :rating_more_than, lambda {|r| where("rating >= ?", r)}  
	scope :rating_less_than, lambda {|r| where("rating <= ?", r)}  

	def self.content_more_than_100_c
		where("length(descriptions) > 100")
	end
	def to_param
   		title
  	end

end

problem5/app/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
	before_filter :require_admin_login

	def index
		@articles=Article.select("articles.id, users.username,articles.title,articles.descriptions").joins(:user).paginate(:page => params[:page], :per_page => 5)
	end
	def new
		@article=Article.new
	end
	def create
		@user = User.find(session[:user_id])
		@article = Article.new(article_params)
		@article.user = @user
		
		if @article.save 
			redirect_to admin_article_path(@article)
		else
			render 'new'
		end
	end
	
	def edit
		@article = Article.find_by_title(params[:id])
	end
	def update
		@article = Article.find_by_title(params[:id])
		if @article.update(article_params)
			redirect_to admin_article_path(@article)
		else
			render 'edit'
		end
	end
	def destroy
		@article=Article.find_by_title(params[:id])
		if @article.destroy
			flash[:notice] = "Article successfully deleted"	
		else
			flash[:error] = "Delete failed"
		end
		redirect_to admin_articles_path
		
	end

	private 
	def article_params
		params.require(:article).permit(:title, :descriptions)
	end

end

problem5/app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
	before_filter :find_article, :only => [:edit, :update, :show, :destroy]
	before_action :correct_owner,   :only => [:edit, :update, :destroy]
	def new
		@article=Article.new
	end
	def index
		@articles=Article.all.paginate(:page => params[:page], :per_page => 5)

	end

	def create
		@user = current_user
		@article=Article.new(article_params)
		@article.user=@user
		
		if @article.save 
			flash[:notice]="Article created"
			redirect_to @article
		else
			render 'new'
		end
	end
	def show
		@comment = @article.comments.build
	end
	def edit
		@article = Article.find_by_title(params[:id])
	end
	def update
		if @article.update(article_params)
			flash[:notice]="Article updated"
			redirect_to @article
		else
			render 'edit'
		end
	end
	def destroy
		@article.destroy
		flash[:notice]="Article deleted"
		redirect_to current_user
	end
	
	private 
	def article_params
		params.require(:article).permit(:title, :descriptions)
	end
	def find_article
      @article = Article.find_by_title(params[:id])
      if @article.nil?
        flash[:notice] = "Cannot find the post"
        redirect_to articles_url
      end
    end
	

	

end

problem5/app/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

problem5/app/app/helpers/articles_helper.rb
module ArticlesHelper
end

problem5/app/app/views/admin/articles/edit.html.erb
<div class="page-header">
  <h3>Edit Article</h3>
</div>
 
<%= render 'articles/form' %>
 

problem5/app/app/views/admin/articles/index.html.erb
<div class="page-header">
  <h3>Articles</h3>
  
  <%= link_to 'New article ', new_admin_article_path(session[:user_id]), :class => "btn btn-primary" %>
  
</div>
<div class="row">
  <div class="span12"> 


  <table class="table table-striped custab">
    <thead>
        <tr>
            <th>Articles Title</th>
            <th>Description</th>
            <th>Writer</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= truncate(article.descriptions, :length => 50) %></td>
      <td><%=article.username%></td>
      <td><%= link_to 'Show', article_path(article.title) %>
       <%= link_to "Edit", edit_admin_article_path(article)%> <%= link_to 'Delete', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    </tbody> 
    </table>  
    <center><%= will_paginate @articles %></center>
      
  </div>
</div>

problem5/app/app/views/admin/articles/new.html.erb
<div class="page-header">
  <h3>Create New Article</h3>
</div>

<%= render "articles/form"%>

problem5/app/app/views/admin/articles/show.html.erb
 <div class="row">
  <div class="span12">
    <div class="row">
      <div class="span12">
        <h4><strong><a href="#"><%=@article.title %></a></strong></h4>
          By <%=link_to "#{@article.user.username}", user_path(@article.user.username) %>
          | <%=time_ago_in_words(@article.created_at)%> ago
          | <span id="sum_comment"><%=@article.comments.count%></span> <a href="#" id="just">Comments</a>
      </div>
    </div>
    <div class="row">
     
      <div class="span12">      
        <p>
          <%=@article.descriptions%>
        </p>
      
      </div>
    </div>

  </div>
</div>
<hr>
  <div class="row">
  <div class="span6">
    <h4>Comments: </h4>
    <div id="comments">
    <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div><br /><br />
  </div>
   </div>
  <div class="row">
   <div class="" id="message">
      <p class="comment_message"></p>
    </div>
    <div class="span8 givecomment">
      <legend>Add comment</legend>
      <%= form_for [@article, @comment], :remote =>true do |f| %>
        <%= f.text_area :content, :class => "span8" %>
        <%= f.submit 'Post a comment', :class => 'btn btn-primary' %> <%= link_to 'Back', articles_path, :class => "btn" %>
      <% end %>
    </div>
  </div>