problem5/app/config/routes.rb
App::Application.routes.draw do
  get "sessions/new"
 
    resources :articles do
      resources 'comments'
    end
  resources :users do
    resources 'articles'
  end
  resources :countries
  
  get 'sign_up' => 'users#new', as: :sign_up
  get 'log_in' => 'sessions#new', as:  :log_in
  get 'log_out' =>'sessions#destroy', as: :log_out
  post 'post_login' => 'sessions#create', as: :post_login 
  
  resources :sessions
  resources :categories
  resources :products
  
  namespace :admin do
    resources :articles
    resources :products
    resources :categories
    resources :countries
    resources :users
  end
  

  root 'articles#index'

end

problem5/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div class="navbar">
				<div class="navbar-inner">
					<div class="container-fluid">
						 <a data-target=".navbar-responsive-collapse" data-toggle="collapse" class="btn btn-navbar"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a> <a href="#" class="brand">App</a>
						<div class="nav-collapse navbar-responsive-collapse in collapse">
							<ul class="nav">
							<%=raw(display_menu)%>
								
							</ul>
							<ul class="nav pull-right">
								<li class="divider-vertical">
								</li>
								<li>
									<%= raw(show_current_user) %>
								</li>
							</ul>
						</div>
						
					</div>
				</div>
				
			</div>	
			<%=raw(message_notice_display)%>
</header>
<div class="container">
			<%=raw(message_notice_header)%>
	<%= yield %>

	<footer>
		
	</footer>
</div>

</body>
</html>

problem5/app/app/views/layouts/welcome.html.erb
<li>
									<% if session[:user_id] %>
									  <li class="dropdown">
									 <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%=session[:username]%><strong class="caret"></strong></a>
									<ul class="dropdown-menu">
										<li>
											<%= link_to("Profile", user_path(session[:username])) %>
										</li>
										<li>
											<%= link_to("Logout", log_out_path) %>
										</li>
										
									</ul>
								</li>
									<% else %>
										<li><%= link_to("Signup", sign_up_path, "data-no-turbolink" => true) %></li>
										<li><%= link_to("Login", log_in_path) %></li>
									  
									<% end %>
								</li>